### ISSUE TITLE
JupyterLab 1.1.3 and 1.1.4 breaks the DataFrame viewer

### ISSUE THREAD

**Issue by euanmacinnes** [lckr/jupyterlab-variableInspector#115] opened 2019-09-19 07:24 UTC
JupyterLab 1.0.4 worked just fine, but I needed to upgrade after issues with the tags etc..

The main Variable Inspector works fine, but anything that views an array displays incorrectly, showing only the row index, and never any columns.

![Capture](https://user-images.githubusercontent.com/54568886/65222346-736ce280-daf1-11e9-8334-55026c8fb8a1.JPG)

Code to duplicate:

(Python)

data = np.array([['','Col1','Col2'],
                ['Row1',1,2],
                ['Row2',3,4]])

**Comment by lckr** [comment] 2019-10-11 18:28
Thanks for your patience. I tried to reproduce this, but for it works as intended (Showing the complete data in the grid viewer).
Maybe a reinstall might help you.

Closing this for now. If you still encounter this, feel free to re-open.

**Closed by lckr** 2019-10-11 18:28 UTC
