### ISSUE TITLE
variable inspector breaks when kernal is restarted in jupyter lab

### ISSUE THREAD

**Issue by ybagdasa** [lckr/jupyterlab-variableInspector#120] opened 2019-10-28 19:31 UTC
Running in Jupyter Lab1.0.2 on firefox 70 (64-bit) on Ubuntu 18.04.

I installed and enabled the inspector through the lab Extension Manager. The problem arises whenever I restart the kernal. The inspector never readies again after that.
![Screenshot from 2019-10-28 12-29-49](https://user-images.githubusercontent.com/5349813/67711243-cf434a80-f97e-11e9-9c98-6b4eff9f4897.png)

**Comment by arteagac** [comment] 2019-11-14 07:58
Similar Issue in JupyerLab v1.1.4 on Chrome 78. The "Restarting Kernel" message never goes away. **It works again when I disable the extension and refresh the browser and then enable it back.**  

![image](https://user-images.githubusercontent.com/13966395/68837271-131d9b80-0671-11ea-9ec9-feb96ae3c7c6.png)

**Comment by flying-sheep** [comment] 2019-12-13 10:57
Also works when closing and reopening the notebook

**Comment by mattmusich** [comment] 2020-01-09 20:56
Similar issue in JupyterLab Version 1.2.4 on Chrome Version 79.0.3945.88

**Comment by mathematicalmichael** [comment] 2020-02-13 14:44
having the same issue in 1.2.4 on Safari

**Comment by lckr** [comment] 2020-03-19 18:51
The current version updated to work with jupyterlab 2.0 should now work as intended and correctly reconnect to restarted kernels.

**Closed by lckr** 2020-03-19 18:51 UTC

**Comment by 276562578** [comment] 2020-10-10 05:37
jupyterlab 2.28 has the same issue
