### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by pkozela** [lckr/jupyterlab-variableInspector#59] opened 2018-10-10 13:39 UTC
I notice a quite important impact on performance when I activate variable inspector.

Basically, some cells that should execute very quickly, hangs for 5-10 seconds before executing. I didn't found any pattern though - it seems like it can randomly happen (quite often thought).

It seems that this is happening when there is a variable that's a big list of strings and I open the variable inspector at least once. For instance, I do this dumb test:

`toto = []
for i in range(500*1000):
    toto.append(100*str(i))`

Then I have 10 cells below with:
`print(datetime.datetime.now())`

that I execute quickly. Somewhere in the middle it will hang.

**Comment by ruaridht** [comment] 2018-10-18 09:44
I am also experiencing a significant slowdown when this addon is enabled. For me it is most cell executions that are affected, no matter the simplicity. I can also see that the CPU is under relatively high load.

I'm using JupyterLab 0.34.9.

**Comment by lckr** [comment] 2018-10-18 11:48
Thanks for your reports.
I'm currently quite busy with university but will try to take a look at it this weekend.

**Comment by dhirschfeld** [comment] 2018-10-25 11:08
Unfortunately this is making JupyterLab nearly unusable for me.

This appears to manifest when I have a notebook with a number of very large variables (mostly DataFrames) in memory.

Testing a simple variable assignment with this extension disabled:

![before](https://user-images.githubusercontent.com/881019/47496231-88b59e80-d899-11e8-979b-5685e08463a6.gif)

...as you would expect instantaneous response (note execution counter).

After enabling this extension:

![after](https://user-images.githubusercontent.com/881019/47496281-b13d9880-d899-11e8-9b09-620bf3cbe5fd.gif)

...approximately 10s for a simple variable assignment. The (kernel) timing info appears to imply that this is all in the frontend.

**Comment by lckr** [comment] 2018-10-25 13:00
Hey @dhirschfeld,
I tried to reproduce this behavior by creating multiple large np arrays from a random gaussian distribution but I could not notice a delay even when filling the 8gb ram of my machine with such matrices. 
I tested this for both the console and notebook and used a python3 kernel.

Can you give me some more information about how to reproduce this bug? For example python version, size and shape of your variables as well as available memory would be interesting.

Thanks in advance.

**Comment by dhirschfeld** [comment] 2018-10-25 20:06
I'll see if I can create a repro...

**Comment by lckr** [comment] 2018-10-26 18:33
I managed to reproduce the issue. As far as I can say now, this delay is only noticeable when using large pd DataFrames. 
The issue is a filter operation in the kernel side code which uses the string representation of an object to determine if an object should be shown in the inspector or not. Unsuprisingly, this is very inperformant for larger dataframes.

A fix should be ready tomorrow.

**Comment by lckr** [comment] 2018-10-27 18:39
Hey, 
I just merged a fix into the master. According to my tests, this should solve the issue with dataframes. 
If you encounter further slow downs, please let me know.

**Closed by lckr** 2018-10-27 18:39 UTC
Labels: bug
