### ISSUE TITLE
R Kernel is not recognized

### ISSUE THREAD

**Issue by quirm** [lckr/jupyterlab-variableInspector#81] opened 2019-03-26 18:34 UTC
I'm using "R version 3.5.3" kernel in JupyterLab and when I open variable inspector from an R notebook, it opens it with ". Language currently not supported." message. Python3 kernel works fine.

I tried changing following in `kernelconnector.ts` and it seems to fix the problem and correctly recognize and inspect R Kernel:
```js
get kernelname(): string {
-    return this._session.kernel.name;
+    return this._session.kernel.info.language_info.name;
}
```

Not sure whether it's the right approach though.

**Comment by lckr** [comment] 2019-04-13 16:53
Hey, did you try reinstalling this extension? According to git-blame we're using `_session.kernel.info.language_info.name;` since 9 months ;-)

**Comment by quirm** [comment] 2019-04-13 16:57
I used the latest version from the master branch. When I check the code, I can see it only for `kerneltype()` which had been changed in past but not for `kernelname()` getter:

https://github.com/lckr/jupyterlab-variableInspector/blob/master/src/kernelconnector.ts#L56

**Comment by lckr** [comment] 2019-04-13 17:17
Ah, you're right. I got them confused.
It seems like this property got moved to `language_info.name`. 
If you want, you can open a pull request with your fix.

**Comment by lckr** [comment] 2019-04-24 10:01
I just took another look and still cannot reproduce this issue.
Furthermore, we only depend on `kerneltype()` to decide whether a kernel is supported or not. Therefore it should be independent of `kernelname()`.
Closing this for now, but if you still have issues, can you check if your kernel returns something other than `R` for `.kernel.info.language_info.name`?

**Closed by lckr** 2019-04-24 10:01 UTC
